// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGAejlobb4F1Y8cDtfL46TrpF8UMDuAbA',
    appId: '1:843413589602:web:8916a6bbf51a462628cb3b',
    messagingSenderId: '843413589602',
    projectId: 'petzy-9fe50',
    authDomain: 'petzy-9fe50.firebaseapp.com',
    storageBucket: 'petzy-9fe50.firebasestorage.app',
    measurementId: 'G-29D7Y6V96K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5IGLU4UnmE156sjPvEWfnoS33GjFokq4',
    appId: '1:843413589602:android:1367b9f8718a3a0928cb3b',
    messagingSenderId: '843413589602',
    projectId: 'petzy-9fe50',
    storageBucket: 'petzy-9fe50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJhToO21ph3ys6scqf4xl4ZwJMxCEEEBA',
    appId: '1:843413589602:ios:474a9e4388893d9928cb3b',
    messagingSenderId: '843413589602',
    projectId: 'petzy-9fe50',
    storageBucket: 'petzy-9fe50.firebasestorage.app',
    androidClientId: '843413589602-afbgov18ddslfd5nigqtb2ech73pm05g.apps.googleusercontent.com',
    iosClientId: '843413589602-pni4fitqtvc52gaprh0parqjh1otahg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.petzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJhToO21ph3ys6scqf4xl4ZwJMxCEEEBA',
    appId: '1:843413589602:ios:474a9e4388893d9928cb3b',
    messagingSenderId: '843413589602',
    projectId: 'petzy-9fe50',
    storageBucket: 'petzy-9fe50.firebasestorage.app',
    androidClientId: '843413589602-afbgov18ddslfd5nigqtb2ech73pm05g.apps.googleusercontent.com',
    iosClientId: '843413589602-pni4fitqtvc52gaprh0parqjh1otahg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.petzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGAejlobb4F1Y8cDtfL46TrpF8UMDuAbA',
    appId: '1:843413589602:web:1ade4e2b4ffda15128cb3b',
    messagingSenderId: '843413589602',
    projectId: 'petzy-9fe50',
    authDomain: 'petzy-9fe50.firebaseapp.com',
    storageBucket: 'petzy-9fe50.firebasestorage.app',
    measurementId: 'G-S5C1151ERJ',
  );
}
